# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build --if-present
    - run: npm test
    - name: SSH Remote Commands
    # You may pin to the exact commit or the version.
    # uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.SSH_ADDRESS_IP}}
        port: 22
        username: ${{secrets.SSH_USER}}
        password: ${{secrets.SSH_PASSWORD}}
        script: |
          pm2 delete all
          cd codespaces-express
          git pull origin main
          npm install
          pm2 start index.js
          
          
          
        
